server:
  profiles:
    active: test
  port: 6001
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka3001.com:3001/eureka/,http://eureka3002.com:3002/eureka,http://eureka3003.com:3003/eureka
  instance:
    instance-id: client-1
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1    #给服务端发送心跳包  30
    lease-expiration-duration-in-seconds: 3   #多久没发送心跳包,才认为服务挂了  默认 90
spring:
  application:
    name: client

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream